"""empty message

Revision ID: 272f0f9d0dfc
Revises: 7151c81e7d27
Create Date: 2021-12-20 13:37:59.561533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272f0f9d0dfc'
down_revision = '7151c81e7d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_constraint('post_title_key', 'post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_title_key', 'post', ['title'])
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
