"""empty message

Revision ID: 5fc1cae778a5
Revises: 76da665b487b
Create Date: 2021-12-19 10:11:51.264521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc1cae778a5'
down_revision = '76da665b487b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.Column('dislike', sa.Boolean(), nullable=True),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.Column('commentId', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commentId'], ['post_comments.id'], ),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('post_comments', 'like')
    op.drop_column('post_comments', 'dislike')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('dislike', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('post_comments', sa.Column('like', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('post_likes')
    # ### end Alembic commands ###
