"""empty message

Revision ID: 76da665b487b
Revises: 1df7d31b18bf
Create Date: 2021-12-18 23:47:05.447101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76da665b487b'
down_revision = '1df7d31b18bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('like', sa.Boolean(), nullable=True))
    op.add_column('post_comments', sa.Column('dislike', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_comments', 'dislike')
    op.drop_column('post_comments', 'like')
    # ### end Alembic commands ###
