"""empty message

Revision ID: fcc3f91de4f2
Revises: 5fc1cae778a5
Create Date: 2021-12-19 14:50:21.097433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc3f91de4f2'
down_revision = '5fc1cae778a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_likes')
    op.add_column('post', sa.Column('like', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('dislike', sa.Boolean(), nullable=True))
    op.add_column('post_comments', sa.Column('like', sa.Boolean(), nullable=True))
    op.add_column('post_comments', sa.Column('dislike', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_comments', 'dislike')
    op.drop_column('post_comments', 'like')
    op.drop_column('post', 'dislike')
    op.drop_column('post', 'like')
    op.create_table('post_likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('like', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dislike', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('postId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['commentId'], ['post_comments.id'], name='post_likes_commentId_fkey'),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], name='post_likes_postId_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], name='post_likes_userid_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_likes_pkey')
    )
    # ### end Alembic commands ###
